Dado un vector A =< a1, a2, . . . a6 > en donde ∀i : ai ∈ N y ∀i, j : i 6=
j =⇒ ai 6= aj . Se define un conjunto de datos en donde cada caso X =<
x1, x2, . . . x6 > cumple con $x_i \in U(−a_i, a_i)$. Es decir, cada caso pertenece a un
hiper-rectángulo con todos sus lados de diferente tamaño según una distribución
aleatoria uniforme en un intervalo dado por A.
Se pide resolver los siguientes puntos utilizando primero la regla de Oja y
luego la de Sanger, de forma que sea posible comparar los resultados y extraer
conclusiones.
1. Entrene una red de 6 entradas y 4 salidas presentando como entrada puntos
de X. Realice varias corridas con distintos pesos iniciales.
2. Analice los vectores de pesos obtenidos. Verifique las propiedades vistas
en las clases teóricas.
3. Teniendo en cuenta que la varianza de las proyecciones sobre los ejes cartesianos es $a^2_i / 3$
en cada caso y que la matriz de covarianzas es diagonal
(verifíquelo), ¿cuáles son las cuatro primeras componentes principales?
4. Calcule las salidas de la red para los puntos utilizados para el entrenamiento. Para cada salida, calcule la media y la varianza. Analice y justifique
los resultados obtenidos.
5. ¿Qué ocurre si a_i = a_j para algún par i, j?


In [1]:
import numpy as np
from ahns import AprendizajeHebbianoNoSupervisado, Caca

In [2]:
A = np.random.uniform(-100, 100, (1, 6))[0]

In [3]:
X = np.random.uniform(-A, A, (500, 6))

In [4]:
X_norm = (X-X.mean(0))/X.std(0)

In [5]:
modelo = AprendizajeHebbianoNoSupervisado(6, 4, 'sanger', 0.0005)
modelo.fit(X_norm)
print(modelo.w)

[[ 0.52682138  0.22317068 -0.41329109  0.17666802]
 [ 0.40588183 -0.00610857  0.44100032 -0.77387366]
 [-0.47973353  0.53210323 -0.12342078 -0.17555275]
 [ 0.26925384 -0.40595355 -0.5983821  -0.18846093]
 [-0.19706976 -0.66218346  0.28749164  0.23216592]
 [-0.46599181 -0.25442575 -0.42380851 -0.5007017 ]]


## Punto 3

In [20]:
matriz = X

print(np.cov(matriz.T))
print((np.diag(np.cov(matriz.T)) - A * A / 3).mean())

[[ 1.48355709e+03  3.08793240e+00 -1.39047276e+00  1.09871218e+02
  -9.14290201e+01 -3.31524034e+01]
 [ 3.08793240e+00  3.49321598e+01 -3.23155912e-01 -2.59347947e+00
  -1.92454770e+00 -5.68162291e+00]
 [-1.39047276e+00 -3.23155912e-01  1.08086600e+00 -3.48033273e+00
  -2.03750531e+00  9.04497016e-01]
 [ 1.09871218e+02 -2.59347947e+00 -3.48033273e+00  2.66451291e+03
   6.89214302e+00  3.65884796e+01]
 [-9.14290201e+01 -1.92454770e+00 -2.03750531e+00  6.89214302e+00
   1.00709785e+03  1.85114204e+01]
 [-3.31524034e+01 -5.68162291e+00  9.04497016e-01  3.65884796e+01
   1.85114204e+01  3.31250084e+02]]
-3.3631790848448513


In [ ]:
no me salio la verdad

## punto 4

In [14]:
activaciones = np.dot(X, modelo.w)
print(activaciones.mean(0))
print(activaciones.std(0))

[ 0.39245259 -0.30562573  0.49731383  1.29854635]
[28.02262644 31.70210534 37.83873251 16.92563496]
