Dadas 2 variables aleatorias de distribución uniforme $u_1, u_2 \in U(−1, 1)$ y las
siguientes matrices:
(coso)

Generar tres conjuntos de datos $X_1, X_2$ y $X_3$ dados por $X_i = [u_1, u_2]^T · M_i$
para entrenar varias redes hebbianas de 3 unidades de entrada y 2 de salida con
las reglas de Oja y Sanger.
1. Comparar las matrices de pesos con las matrices $M_i$ utilizadas para generar
los datos de entrada.
2. Comparar los valores pertenecientes a $X_i$ con los valores $Y$ devueltos por
la red.
3. Comparar los valores pertenecientes a $X_i$ con los resultantes de hacer $Y · W_i^T$

4. ¿Qué va a suceder si se utilizan los tres conjuntos de datos para entrenar
la misma red?



In [22]:
import numpy as np
from ahns import AprendizajeHebbianoNoSupervisado

In [23]:
M1 = np.array([[4, 0, 0.5], [0, 2, 0.5]])
M2 = np.array([[1, 0.5, 0.75], [0.5, 1, 0.75]])
M3 = np.array([[1, 1, 1], [0.5, 0.5, 0.5]])

In [24]:
""" X1 = np.dot(np.random.uniform(-1, 1, (1, 2)), M1)
X2 = np.dot(np.random.uniform(-1, 1, (1, 2)), M2)
X3 = np.dot(np.random.uniform(-1, 1, (1, 2)), M3) """
# esta mal el enunciado???
X1 = np.random.uniform(-1, 1, (1, 2)).T * M1
X2 = np.random.uniform(-1, 1, (1, 2)).T * M2
X3 = np.random.uniform(-1, 1, (1, 2)).T * M3
print(X1)

[[-2.65551416 -0.         -0.33193927]
 [ 0.          1.27896586  0.31974147]]


In [30]:
modelo = AprendizajeHebbianoNoSupervisado(3, 2, 'sanger', 0.001)
modelo.fit(X1)
print(modelo.w)
print(M1)

[[-0.99194701  0.03498979]
 [-0.00928746 -0.96991979]
 [-0.12631524 -0.23852606]]
[[4.  0.  0.5]
 [0.  2.  0.5]]
